### ISSUE TITLE
[WCAG] Voice Over on Homepage

### ISSUE THREAD

**Issue by arielkidwell** [vigetlabs/pointless-corp-astro#25]
**Details**
- This is probably worth another look. It worked smoother on the project detail pages than it did the homepage for me. It struggled to move into the main website area, and once I got it there, it tended to jump around and miss quite a bit of the headlines, etc.

**Comment by ten1seven** [comment]
@arielkidwell I made one teak but am generally finding the reading smoother in Safari. I recommend using Safari + VoiceOver because they're designed to work together and they're the [most popular MacOS browser/screen reader combo](https://webaim.org/projects/screenreadersurvey10/#browsercombos). Admittedly, Windows is much more popular but we currently don't have a good team-wide way to test in that environment.

**Comment by arielkidwell** [comment]
@ten1seven Another great tip - thank you for flagging! Works great in Safari.
